### PR TITLE
Fix typos in MD046 Docs

### PR DESCRIPTION
**Pull request by waylan**
Also cleared up some awkward wording.

I would add an explanation of how the `consistent` option works, but I'm not sure what that is. How does it determine which style is the preferred? The first style it encounters or the style used most often?

### CODE REVIEW

**Comment by copperwalls** [comment]
@waylan There’s still a typo 🙂 (See #216)

**Comment by waylan** [comment]
Ah, yep, I missed one. Fixed now.

**Comment by psyomn** [comment]
Hi, thanks. Can you rebase, and this should be good to go.

**Comment by psyomn** [comment]
If you can squash into one commit, I'll go ahead and merge it. Thanks!

**Comment by waylan** [comment]
Finally found some time to make a local clone to rebase and swash this. I sure do like GitHub's rebase and swash features for those quick edits on the website. Not sure why that wouldn't have worked here.

**Comment by psyomn** [comment]
Thank you!

**Pull request merged**
