### PR TITLE
[MD046] Enforce a code block style

### PR DESCRIPTION
**Pull request by jaymzh**

### CODE REVIEW

**Comment by jaymzh** [comment]
The tests are failing... but they seem to be also failing on master.. :/

**Comment by jaymzh** [comment]
OK at least SOME of these are my fault... working on it :)

**Comment by DavidAnson** [comment]
`MD042` is already used by the Node implementation for a different purpose: https://github.com/DavidAnson/markdownlint#rules--aliases

Would you mind changing to an unassigned value so this rule can be implemented there under the same name?

**Comment by jaymzh** [comment]
Sure

**Comment by DavidAnson** [comment]
Thanks! Should this rule have a “consistent” mode as default like some other rules do?
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md003---header-style

**Comment by jaymzh** [comment]
I prefer to actually enforce a style, but I guess if people want that I can do it.

**Comment by jaymzh** [comment]
Added a `consistent` option.

I didn't make it the default though - unlike headers, code blocks have clear reasons to prefer one over the other. The biggest is that you can specify a language in fenced, but you cannot in indent-based ones. Further '4 spaces' is a thing you can't actually SEE so it's easy to screw up. Finally, fenced is just generally more common.

**Comment by jaymzh** [comment]
@DavidAnson - does that explanation make sense? Is that OK?

All - Any other changes needed? Any other concerns? I'd love to get this merged.

Thanks!

**Comment by DavidAnson** [comment]
Yes, that makes sense to me. I still think there is wisdom in having a flexible default, but defer to you as the person who implemented this. (Personally, I agree with your approach to encouraging the use of fenced blocks.) Regarding signing off or accepting the pull request, I do not consider myself authoritative for this repository, and only drop in where I see an opportunity to make the cross platform experience more seamless. Thanks for your help!

**Comment by jaymzh** [comment]
I'll tag someone who looks like a maintainer: @psyomn ?

**Comment by jaymzh** [comment]
@psyomn  - next up? :)

**Comment by jaymzh** [comment]
Monday morning ping, @psyomn  :)

**Comment by psyomn** [comment]
Thanks for the thorough tests. Cheers!

**Pull request merged**
