### PR TITLE
Improve RuboCop use

### PR DESCRIPTION
**Pull request by bquorning**
## Description

1. Use a newer version of RuboCop, and lock the version a bit stricter than before.
2. Remove scripts/run_rubocop.sh and run `bundle exec rubocop` on CI. I don't know what was the rationale for [adding that wrapper script](https://github.com/markdownlint/markdownlint/commit/b84687a00d57fccc1ea985aa0f0cd8cbce5ae2fe#diff-ebed48dc423f32a03f5fb07464e5aab9580ef282b15919ec8acc4eedb49742b7) in the first place.
3. Enable the `Style/LineEndConcatenation` cop and fix the offenses.
4. Disable the entire `Metrics` section of cops, instead of disabling each cop one by one.

Let me know if you prefer having the changes in 4 separate commits.

## Related Issues

None

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (non-breaking change that does not add functionality but updates documentation)
- [x] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/markdownlint/markdownlint/blob/master/CONTRIBUTING.md) document.
- [x] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/)
- [x] Feature branch is up-to-date with `master`, if not - rebase it
- [ ] Added tests for all new/changed functionality, including tests for positive and negative scenarios
- [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences

### CODE REVIEW

**Review by jaymzh — CHANGES_REQUESTED** [review]
> Use a newer version of RuboCop, and lock the version a bit stricter than before.

:+1: 

> Remove scripts/run_rubocop.sh and run bundle exec rubocop on CI. I don't know what was the rationale for [adding that wrapper script](https://github.com/markdownlint/markdownlint/commit/b84687a00d57fccc1ea985aa0f0cd8cbce5ae2fe#diff-ebed48dc423f32a03f5fb07464e5aab9580ef282b15919ec8acc4eedb49742b7) in the first place.

It was to properly handle various cases where you want to give paths to files and have it do the right thing, automatically.

> Enable the Style/LineEndConcatenation cop and fix the offenses.

We actually prefer `+` to `\` - backslash in Ruby has weird consequences that are not always obvious and I've always found it strange the styleguide suggests it.

> Disable the entire Metrics section of cops, instead of disabling each cop one by one.

Sounds good, thanks.

**Comment by bquorning** [comment]
> It was to properly handle various cases where you want to give paths to files and have it do the right thing, automatically.

If you pass the paths to files/folders, `bundle exec rubocop` should also do the right thing. Do you have an example of how it has failed to work?

> We actually prefer `+` to `\` - backslash in Ruby has weird consequences that are not always obvious and I've always found it strange the styleguide suggests it.

I think the reason for the styleguide suggesting `/` instead of `+` is to reduce the number of allocated objects (`+` will allocate a new object for the resulting string). The weird consequences you refer to is perhaps when building a multiline string where not all lines are literal strings, e.g. this won’t work:
```rb
"foo" \
bar.to_s
```
Anyway, object allocation shouldn’t be a problem during error handling, so I’m ok with reverting those changes.

**Review by jaymzh — APPROVED** [review]
can't find whatever case it was, so wfm.

**Comment by jaymzh** [comment]
Thanks!

**Pull request merged**
