### PR TITLE
Fix MDL'ing our own files

### PR DESCRIPTION
**Pull request by jaymzh**
We attempted to exclude a rule but excluded all rules.

Filed bug #369 to fix that.

Meanwhile, this turns on our rules.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (non-breaking change that does not add functionality but updates documentation)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/markdownlint/markdownlint/blob/master/CONTRIBUTING.md) document.
- [x] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/)
- [x] Feature branch is up-to-date with `master`, if not - rebase it
- [x] Added tests for all new/changed functionality, including tests for positive and negative scenarios
- [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences

### CODE REVIEW

**Comment by jaymzh** [comment]
This will require fixing of a lot of our own MD. :)

**Comment by jaymzh** [comment]
This is sitting on the list-fixing commit for now. Still need more work probably.

**Comment by jaymzh** [comment]
The tests seem to actually pass now, except it's not ignoring the requested files. Filed an upstream bug:

https://github.com/actionshub/markdownlint/issues/15

**Comment by NaomiReeves** [comment]
This looks sane but I think you have an errant commit from #373

**Comment by jaymzh** [comment]
also filed https://github.com/actionshub/markdownlint/issues/16 upstream...

**Comment by jaymzh** [comment]
OK @NaomiReeves - this is ready for review finally.

**Comment by jaymzh** [comment]
Ping @NaomiReeves

**Review by NaomiReeves — APPROVED** [review]

**Pull request merged**
