### PR TITLE
Fix lint MD039 checking for nodes inside link text

### LINKED ISSUE #102: MD039 Spaces inside link text
This rule is triggered on links that have spaces surrounding the link text

It also triggers when I use an emphasis within a link text.

Example:

``` markdown
[The **test** web site](http://www.example.com/)
```

Not sure if that is a bug but I wanted to report it.

test.md:2: MD039 Spaces inside link text

### LINKED ISSUE #103: Also look for `.mdlrc` up each dir from the working directory
This allows for VCS-managed, per project configuration.

`~/.mdlrc` may either be considered as a fallback, or configuration should be merged, giving it lower priority.

### PR DESCRIPTION
**Pull request by psyomn**
Closes #102

### CODE REVIEW

**Comment by psyomn** [comment]
Let me know if you're looking for a maintainer.

**Comment by Dorian** [comment]
@psyomn I'm up for maintaining a community fork

**Comment by psyomn** [comment]
Sounds good. Let me know when you're ready and I'll submit a PR there as well.

**Comment by Dorian** [comment]
I'm ready, I'm making mardownlint part of rubocop's CI (mardown is generated so it's not so easy) 

Also made a bunch of scripts to autocorrect lints, E.g. `mdl --auto-correct / -a` equities be great

**Comment by mivok** [comment]
@psyomn I've sent you an email directly re: maintainership. I'd hold off on a fork for the moment.

**Comment by Dorian** [comment]
@mivok Nice, thanks for replying, this is a neat project, I hope it will move to an org

**Comment by Kristinita** [comment]
@psyomn , @mivok , please, add this changes in new release.

Thanks.

**Comment by psyomn** [comment]
@Kristinita sorry for the late reply. Busy with life things. I'll try to have something done by this weekend. (Thanks for the detailed issues you've posted btw)

**Comment by Kristinita** [comment]
@psyomn , ping. At April 2018 last release [**still dating August 2016**](https://rubygems.org/gems/mdl/versions).

Thanks.

**Pull request merged**
