### PR TITLE
Fix issue numbers false positives

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Not sure if this could cause any problems, but it seems to fix the issue I'm having...

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Friendly ping :)

**Comment by psyomn** [comment]
Saw this, thanks. I'm going to try and have something soon.

**Comment by psyomn** [comment]
Hey there, sorry for the late follow up. I'm going to try and get something done this weekend perhaps. I'd like to understand the nature of the change a little more before I merge.

**Comment by deivid-rodriguez** [comment]
Of course. It's a common github idiom to link to issues by prepending the "#" symbol to the issue number, since github "autolinks" it. Currently, that's flagged as an offense since mdl interprets it as a header.

What my changes try to do is considering headers only when they are at the beginning of lines. That allows for usages of "#" like the one described but it also feels like the correct behavior anyways.

**Comment by deivid-rodriguez** [comment]
@psyomn Any news?

**Comment by psyomn** [comment]
Sorry, for delay. Thanks for the writeup, what I meant is that I'm not sure what the recursive thingy does. 

For instance, would this be a valid use case:

```markdown
- #123 
- #1234
    - #12345
```

I think this fails at the moment. If that's okay, I can try and merge soon. Let me know!

**Comment by deivid-rodriguez** [comment]
@psyomn Thanks for having a look!

Well, the use case you present should pass IMO. The current functionality is enough for me (that kind of hashtag nesting seems pretty rare), but the fact that it fails is definitely unexpected. So I'll try to have a look!

**Comment by deivid-rodriguez** [comment]
@psyomn I'm not really sure what I'm doing here, but I think I fixed the issue you mention :)

BTW, it seems like you need to re-add Travis after having renamed the repo.

**Comment by psyomn** [comment]
Thanks, I'll take a look and probably merge tonight!

**Pull request merged**
