### PR TITLE
Several bug fixes

### LINKED ISSUE #133: mdl is broken when ~/.mdlrc is present
For example, I have a `.mdlrc` in my HOME directory, with the following content:

```
rules "~MD013"
```

Then, in a project directory, run mdl, and it will break:

```
$ mdl README.md
/Library/Ruby/Gems/2.0.0/gems/mixlib-config-2.2.1/lib/mixlib/config.rb:47:in `instance_eval': no implicit conversion of Pathname into String (TypeError)
    from /Library/Ruby/Gems/2.0.0/gems/mixlib-config-2.2.1/lib/mixlib/config.rb:47:in `from_file'
    from /Library/Ruby/Gems/2.0.0/gems/mdl-0.3.1/lib/mdl/cli.rb:106:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/mdl-0.3.1/lib/mdl.rb:14:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/mdl-0.3.1/bin/mdl:10:in `<top (required)>'
    from /usr/local/bin/mdl:23:in `load'
    from /usr/local/bin/mdl:23:in `<main>'
```

FYI, I used "specific_install" to install the master branch of markdownlint.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Fixes #133 and #146.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@mivok Could you review this and, if possible, release a version with the latest fixes? Thanks a lot!!

**Comment by deivid-rodriguez** [comment]
@mivok ping

**Comment by deivid-rodriguez** [comment]
@mivok Here it goes, my monthly ping! ;)

**Comment by deivid-rodriguez** [comment]
@mivok :alarm_clock: ping!

**Comment by deivid-rodriguez** [comment]
@mivok I'd like to contribute a bit more to this repo (I just run into #146 and I want to fix it), but I'd like to know whether this is on your radar or not first.

**Comment by deivid-rodriguez** [comment]
Including both fixes here #133 and #146, so I can easily use this branch.

**Comment by deivid-rodriguez** [comment]
Superseded by #148

**Comment by mivok** [comment]
Hi David,

As you've no doubt noticed, I've been extremely busy over the past couple of months and had essentially no time to work on markdownlint. As a result I've been pretty quiet here, and for that I'd like to apologize. I'll spend some time over the next day or so to review your fixes in #148 (and other open PRs too) and get them merged in.

**Comment by deivid-rodriguez** [comment]
No problem, I understand! :+1:

**Pull request closed without merging**
