### PR TITLE
JSON formatter

### LINKED ISSUE #205: RFE: JSON output
It would be great to get JSON-formatted output so this linter can be plugged into other systems more easily.

### PR DESCRIPTION
**Pull request by jaymzh**
Provide a JSON formatted output.

Closes #205

### CODE REVIEW

**Comment by jaymzh** [comment]
Thoughts?

**Comment by jaymzh** [comment]
I'll tag someone who looks like a maintainer: @psyomn ?

**Comment by psyomn** [comment]
I'll try and take a look this weekend; thanks!

**Comment by jaymzh** [comment]
just a gentle reminder, @psyomn

**Comment by psyomn** [comment]
Thanks, this looks good. I'll probably merge tomorrow when I can think a little clearer.

**Comment by jaymzh** [comment]
Awesome, thanks! While you're at it, if you could also review/merge https://github.com/markdownlint/markdownlint/pull/204 I'd appreciate it!

**Comment by psyomn** [comment]
Nice, thanks. I'll tend to the following PR, on the upcoming days.

**Pull request merged**
