### PR TITLE
Fix inner quotes

### LINKED ISSUE #182: Links with double-quotes in them are falsely caught by MD039
Seems to only apply with quotes in the middle and end part of links. When the link is only a double-quoted part, or when the quotes are the start, it does fine.

```text
somasis@seneca:~/ % printf '%s\n' '["quoted parts"](http://example.org)\n' | mdl
somasis@seneca:~/ % printf '%s\n' '[test link "quoted parts"](http://example.org)\n' | mdl
(stdin):1: MD039 Spaces inside link text
somasis@seneca:~/ % printf '%s\n' '[test link "quoted parts" test link](http://example.org)\n' | mdl
(stdin):1: MD039 Spaces inside link text
somasis@seneca:~/ % printf '%s\n' '["quoted parts" test link](http://example.org)\n' | mdl
somasis@seneca:~/ % 
```

### PR DESCRIPTION
**Pull request by psyomn**
Closes #182, #183

### CODE REVIEW

**Comment by psyomn** [comment]
@tram0004 Thanks for the test; I've cherry picked it into this branch and will merge soon.

**Comment by XhmikosR** [comment]
Would it be possible to get a new release with this fix included?

**Comment by XhmikosR** [comment]
@DavidAnson is there any way we could get a new gem version out with this fix?

**Comment by DavidAnson** [comment]
I don’t live in the Ruby world, so I don’t really know what that was involved. Also, I’m not sure I am the permissions to do so? If someone can tell him that I do have permission and provide a set of directions, I could try this, but that should probably be the last resort.

**Comment by XhmikosR** [comment]
@DavidAnson I hear you, I'm not very familiar with Ruby packages either. That being said, this fix is super important and I can't seem to find someone else active. If you do, let's ping someone else.

**Comment by DavidAnson** [comment]
Someone sent me a Twitter DM trying to get in touch with @psyomn - not sure if that was successful.

**Comment by XhmikosR** [comment]
It seems @psyomn is MIA. Is there somebody else who had access to this repo @DavidAnson ?

**Pull request merged**
