### PR TITLE
Add SARIF output

### LINKED ISSUE #458: Output result as SARIF
## Describe the Enhancement:

Currently, the analysis result can be outputted as JSON, having it as SARIF would be helpful to be used with GitHub Code Scanning: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning.

### Impacted Rules:

None.

## Describe the Need:

See above.

## Current Alternative

Convert the JSON output to SARIF.

## Can We Help You Implement This?:

Yes: https://github.com/markdownlint/markdownlint/pull/459.

### PR DESCRIPTION
**Pull request by mathroule**
## Description

- Add an option to output results as [SARIF](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html).
- Introduce a SARIF formatter.
- Align JSON output unit tests with SARIF output.

## Related Issues

- Fix https://github.com/markdownlint/markdownlint/issues/458

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (non-breaking change that does not add functionality but updates documentation)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/markdownlint/markdownlint/blob/master/CONTRIBUTING.md) document.
- [x] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/)
- [x] Feature branch is up-to-date with `master`, if not - rebase it
- [x] Added tests for all new/changed functionality, including tests for positive and negative scenarios
- [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences

### CODE REVIEW

**Comment by mathroule** [comment]
It might be better to replace `--json` and `--sarif` options with a new format option: `--format json` or `--format sarif`.

But it will introduce a breaking change.

**Comment by DavidAnson** [comment]
@mathroule Neat! Out of curiosity, how are you validating the .SARIF output files are correct and work with the GitHub pipeline?

**Comment by mathroule** [comment]
> @mathroule Neat! Out of curiosity, how are you validating the .SARIF output files are correct and work with the GitHub pipeline?

Using this [SARIF validator](https://sarifweb.azurewebsites.net/Validation), with the "GitHub ingestion rules" enabled.

**Comment by mathroule** [comment]
This is how a lint issue looks when reported on GitHub Code Scanning.
Screenshot 2023-06-15 at 09 17 30

**Comment by nbehrnd** [comment]
Note, your commits appear to be formally incomplete; this can block the review of your contribution and an eventual merge into the project.

The project's policy requires each commit to be signed (cf. `CONTRIBUTING.md`) by its author.  One approach to add the DCO, after provision of the commit message, is an additional

```shell
git commit --amend -s
```

For illustration, compare the output running `git log -1` once issued in the master/main branch with same command issued in your feature branch as by [2023-06-14 Wed], commit f281743.  (Initially, I didn't pass this check mark either.)

**Comment by mathroule** [comment]
> Note, your commits appear to be formally incomplete; this can block the review of your contribution and an eventual merge into the project.
> 
> The project's policy requires each commit to be signed (cf. `CONTRIBUTING.md`) by its author. One approach to add the DCO, after provision of the commit message, is an additional
> 
> ```shell
> git commit --amend -s
> ```
> 
> For illustration, compare the output running `git log -1` once issued in the master/main branch with same command issued in your feature branch as by [2023-06-14 Wed], commit [f281743](https://github.com/markdownlint/markdownlint/commit/f28174363eae94482641ee1da2f6e67c9d6321cd). (Initially, I didn't pass this check mark either.)

Oh sorry, my commits were signed with GPG but not signed off, now they have both. Thanks for pointing that.

**Comment by DavidAnson** [comment]
@mathroule At the risk of being a pest, I am curious how you set this up with CodeQL in GitHub as I don't see that done in this PR. I maintain the Node implementation of markdownlint and may add an output formatter for this to markdownlint-cli2 if it's something people want to do. For what it's worth, I already publish a GitHub action which provides code annotations and seems to do nearly the same thing as what you show. I'm curious why someone would choose this approach over an action?

**Comment by mathroule** [comment]
> @mathroule At the risk of being a pest, I am curious how you set this up with CodeQL in GitHub as I don't see that done in this PR. I maintain the Node implementation of markdownlint and may add an output formatter for this to markdownlint-cli2 if it's something people want to do. For what it's worth, I already publish a GitHub action which provides code annotations and seems to do nearly the same thing as what you show. I'm curious why someone would choose this approach over an action?

GitHub Code Scanning and GitHub Actions annotations do not achieve the same goal, even if they look similar.

| | GitHub Code Scanning | GitHub Actions annotations |
|-|------|----|
| UI | Screenshot 2023-06-15 at 19 03 29 | Screenshot 2023-06-15 at 18 33 28 |
| Target | A file belonging to a PR + the "Security" tab of a GitHub repository | A file belonging to a PR |
| Dismissable | Yes image | No |
| Can block a PR | Yes with a check on the pull request Screenshot 2023-06-15 at 19 09 53 | No |

Annotations are mostly informative, while Code Scanning offers a real interaction with the reported alerts.

You can find more info in the GitHub doc: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning

Also, Code Scanning alerts are centralized in the "Security" tab of a GitHub repository, while annotations only appears in a pull request.
Screenshot 2023-06-15 at 18 31 23

Lastly, to upload SARIF data to GitHub, this step can be used in a GitHub Actions workflow:
```yaml
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: markdownlint.sarif
          category: Markdown lint
```

**Comment by mathroule** [comment]
Moreover, since SARIF is a standard, it can be also imported in SonarQube: https://docs.sonarqube.org/9.8/analyzing-source-code/importing-external-issues/importing-issues-from-sarif-reports.

**Comment by DavidAnson** [comment]
@mathroule This is great detail, thank you! It feels like there is a lot of overlap, but I see how SARIF has broader applicability. One thing I disagree with your table, though: a failing GitHub action can "block" a PR in the sense that it shows up next to the button to merge that PR. I'm not sure GitHub actually prevents the merge, but it should be very obvious to anyone merging a PR with failing actions that they are doing so.

**Comment by mathroule** [comment]
> @mathroule This is great detail, thank you! It feels like there is a lot of overlap, but I see how SARIF has broader applicability. One thing I disagree with your table, though: a failing GitHub action can "block" a PR in the sense that it shows up next to the button to merge that PR. I'm not sure GitHub actually prevents the merge, but it should be very obvious to anyone merging a PR with failing actions that they are doing so.

Indeed, SARIF (Static Analysis Results Interchange Format) is a new standard and has broader applications than just GitHub Code Scanning.

Regarding the capability to block a pull request, GitHub Code Scanning provides the ability to add a check directly to a pull request, whereas GitHub Annotations does not have this capability. Consequently, it is up to the repository owner to decide whether to enforce this check or simply bypass it.

**Review by gaborvass-zendesk — APPROVED** [review]

**Comment by DavidAnson** [comment]
@mathroule, I had most of the pieces in place already, so I published an output formatter for `markdownlint-cli2` for SARIF just now: <https://www.npmjs.com/package/markdownlint-cli2-formatter-sarif>

Here’s what it looks like to hook in up to GitHub: <https://github.com/DavidAnson/markdownlint-cli2/commit/37520a53f858705470fd1dbd6183617c2f36f926>

I don’t know how long the data for this deleted test branch will last, but here’s an example report: <https://github.com/DavidAnson/markdownlint-cli2/security/code-scanning?query=is%3Aopen+branch%3Afinalsarif>

The info you shared here was super useful and I used the `.sarif` output files in this PR to inform necessary properties and structure.

Thanks again!

**Comment by mathroule** [comment]
Thanks @DavidAnson for adding SARIF support to `markdownlint-cli2`.

Do you think my PR can be merged into this repo? I can use the node client, but this Ruby client is my preferred choice for now.

**Comment by DavidAnson** [comment]
@mathroule Sorry, I only watch this repo, I don't manage it.

**Review by gaborvass-zendesk — APPROVED** [review]

**Comment by mathroule** [comment]
> Note, your commits appear to be formally incomplete; this can block the review of your contribution and an eventual merge into the project.
> 
> The project's policy requires each commit to be signed (cf. `CONTRIBUTING.md`) by its author. One approach to add the DCO, after provision of the commit message, is an additional
> 
> ```shell
> git commit --amend -s
> ```
> 
> For illustration, compare the output running `git log -1` once issued in the master/main branch with same command issued in your feature branch as by [2023-06-14 Wed], commit [f281743](https://github.com/markdownlint/markdownlint/commit/f28174363eae94482641ee1da2f6e67c9d6321cd). (Initially, I didn't pass this check mark either.)

Thanks @nbehrnd the PR is now using signed commit. Could you please help reviewing the PR?

**Review by jaymzh — APPROVED** [review]
Looks great, thanks!

**Comment by jaymzh** [comment]
@mathroule  - your SARIF tests are failing on main: https://github.com/markdownlint/markdownlint/actions/runs/6374199973/job/17298564200

**Comment by mathroule** [comment]
> @mathroule - your SARIF tests are failing on main: https://github.com/markdownlint/markdownlint/actions/runs/6374199973/job/17298564200

Fixed in https://github.com/markdownlint/markdownlint/pull/469.

**Review by joe10832 — APPROVED** [review]
@markdownlint-autobuild

**Pull request merged**
