### PR TITLE
Allow "changelog-style" header organization

### LINKED ISSUE #175: MD024 (Multiple headers with same content) should only trigger under the same nesting
In my opinion

```markdown
# Change log

## 1.0.0

### Bug fixes
...

### Features
...

### Bug fixes
...
```

should trigger an offense.

But

```markdown
# Change log

## 1.0.0

### Bug fixes
...

### Features
...

## 0.0.1

### Bug fixes
...
```

should not.

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Fixes #175.

I chose to add this as a style (although I made it the default, not sure about that), because the original check can still be useful for some people.

Can styles be configured on a per-file basis, by the way?

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@psyomn Ping!

**Comment by psyomn** [comment]
Welp, newer version seems to be working :).

**Comment by deivid-rodriguez** [comment]
Yeah! :)

**Comment by psyomn** [comment]
Alright will merge if you have no objections!

**Comment by deivid-rodriguez** [comment]
I just wonder about the default. As it is now, it's backwards incompatible... Should probably be switched to `false`?

**Comment by psyomn** [comment]
I think it would be maybe a better idea to have it as `false`, as IIUC, might affect builds that may be depending on linting. This can make people angry, and angry people at code is not good, haha.

**Comment by deivid-rodriguez** [comment]
Yeah, I was having the same thought. I'll flip the default and pick you back when ready. Thanks @psyomn!

**Comment by psyomn** [comment]
No prob! Thanks, and sorry for taking so long

**Comment by deivid-rodriguez** [comment]
@psyomn It's done!

**Comment by deivid-rodriguez** [comment]
> No prob! Thanks, and sorry for taking so long

No worries, I know what it's like, and it hasn't been that long :)

**Comment by psyomn** [comment]
Sweet thanks a lot man!

**Pull request merged**
