### PR TITLE
 Fix travis ci badge

### LINKED ISSUE #201: Renable CI
It seems like there's no longer CI enabled after the repo was renamed.

### PR DESCRIPTION
**Pull request by psyomn**
Fixes #201

### CODE REVIEW

**Comment by psyomn** [comment]
@deivid-rodriguez I think it's working again. lmk, and we'll proceed with your other PR.

**Comment by psyomn** [comment]
Welp, jruby is failing. I'll have to take a look tomorrow more in depth why.

**Comment by deivid-rodriguez** [comment]
Thanks! Latest jruby is 9.1.17.0. Maybe upgrading that will fix it....

**Comment by deivid-rodriguez** [comment]
Up to you, I'm fine with both, just le me know! :+1:

**Comment by psyomn** [comment]
So I cherry picked your commit into this PR; make sure to remove it from yours. I'm going to remove some of my commits in this PR and I'll go ahead and merge if you think this is alright!

**Comment by deivid-rodriguez** [comment]
Yeah! As soon as you merge this I'll rebase my PR!

**Comment by psyomn** [comment]
Thanks!

**Pull request merged**
