### PR TITLE
MD040: Mention how to get no syntax highlighting

### PR DESCRIPTION
**Pull request by lentzi90**
## Description

MD040 requires the use of a language specified for fenced code blocks but lacked clarification on what to use when no specific language was used.  In these cases it is suggested to use `text` as language specifier.

## Related Issues

These are related but not really fixed by this PR.
https://github.com/markdownlint/markdownlint/issues/314
https://github.com/markdownlint/markdownlint/issues/87

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (non-breaking change that does not add functionality but updates documentation)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/markdownlint/markdownlint/blob/master/CONTRIBUTING.md) document.
- [x] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/)
- [x] Feature branch is up-to-date with `master`, if not - rebase it
- [x] Added tests for all new/changed functionality, including tests for positive and negative scenarios
- [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences

### CODE REVIEW

**Review by jaymzh — APPROVED** [review]
Nice, thanks

**Comment by jaymzh** [comment]
@lentzi90 - you're missing a signed-off-by in your commit, see the DCO check.

**Comment by lentzi90** [comment]
@jaymzh could you approve the workflows please?

**Comment by jaymzh** [comment]
Thanks!

**Pull request merged**
