### PR TITLE
Added a link to RULES.md after printing results

### LINKED ISSUE #53: Show a link to RULES.md after results
It'd be nice if the tool would print a link to [RULES.md](https://github.com/mivok/markdownlint/blob/master/RULES.md) after showing the violated rules.

This would make it easier for users that just read e.g. a CI build log to figure out what the rules mean.

### PR DESCRIPTION
**Pull request by akoeplinger**
Fixes #53

### CODE REVIEW

**Comment by exalted** [comment]
I could be cool actually if you could link to related rule directly. GitHub generates an anchor tag for each header in markdown files, such as: https://github.com/mivok/markdownlint/blob/master/docs/RULES.md#md001---header-levels-should-only-increment-by-one-level-at-a-time.

If you could rename titles contain rule names only, then you could simply `"https://github.com/mivok/markdownlint/blob/master/docs/RULES.md#{rule_name}"`.

What do you think?

**Comment by akoeplinger** [comment]
That'd mean you'd need to print the link for each error separately, which I think is a bit overwhelming. IMHO printing the link once and letting the user lookup the rules is a better experience.

**Comment by exalted** [comment]
Fair enough. :clap:

## 

Ali

**Comment by akoeplinger** [comment]
@mivok any updates on getting this merged? Happy to close the PR if it's not something you want in markdownlint 😄

**Comment by psyomn** [comment]
I'm reviewing this and will most likely merge. Perhaps in the spirit of this PR, seeing something like 

```mdl --explain MD033```

would be nice too. The Rust compiler does this and it's pretty handy.

**Comment by akoeplinger** [comment]
Thank you ❤️ 

`mdl --explain MD033` is a great idea!

**Pull request merged**
