### PR TITLE
Fix setext header style with level > 2

### PR DESCRIPTION
**Pull request by xi**
The [markdown styleguide](http://www.cirosantilli.com/markdown-style-guide/#option-header-setex) defines the setext header style to fall back to atx for headers of level 3 or more:

```
Header 1
========

Header 2
--------

### Header 3
```

This currently is reported as an error by `mdl`. I tried to fix it. But be aware: I did not write any ruby in recent years.

### CODE REVIEW

**Comment by mivok** [comment]
Thanks for your contribution! Your ruby looks fine. However, the header_style helper function is intended to identify the style of the header it is passed, rather than provide a list of valid header styles for the document given a header. This is best addressed directly in the rule itself.

I think there are a few options for addressing this:
- Disabling MD003 entirely in your style file or personal settings. This would unfortunately also allow atx style headers that are closed (have hashes at the end) also, which doesn't appear to be what you want.
- Add an option for :setext_with_atx style headers, which would allow both types, with some special casing in the rule like we do with :consistent. This wouldn't perfectly match the style guide as it would allow atx style headers that are level 1 (e.g. `# Header 1`) or level 2 (e.g. `## Header 2`).
- Add the option for :setext_with_atx style headers, where we only allow atx style headers that are level 3 or higher. This is the most complex to implement, but would match what is said in the style guide.

**Comment by xi** [comment]
Thanks for the feedback. However, I feel like there are some misunderstandings:

> the header_style helper function is intended to identify the style of the header it is passed, rather than provide a list of valid header styles for the document given a header.

I did not change the behavior of `header_style`. I added a function `header_styles` and changed the implementation of `header_style` in order to keep the code DRY.

If the functionality would be implemented in the rule itself it would need to duplicate a lot of `header_style`. Do you really prefer that to my proposed implementation?

> Add the option for :setext_with_atx style headers, where we only allow atx style headers that are level 3 or higher. This is the most complex to implement, but would match what is said in the style guide.

AFAIU this is what I implemented, except that I did not create a new option for this. I thought a new option was not necassary because the new behavior is consitent with the style guide and the old behavior was undocumented and untested.

So my two questions to you are:
-   Should I create an option for the new (fixed) behavior?
-   Should I restore the original `header_style` implementation and instead do everything in the rule, possibly duplicating functionality?

**Comment by mivok** [comment]
> AFAIU this is what I implemented

Ah, you're correct. I missed the check for >2 on the atx style and thought the check allowed header levels one and two.

> Should I create an option for the new (fixed) behavior?

Yes - the reason for this is that the markdown style guide isn't the only option out there, and it is possible that people will want the option to only allow setext style headers with no atx style headers at all.

> Should I restore the original header_style implementation and instead do everything in the rule, possibly duplicating functionality?

Yes please, although I suspect you will end up not having to duplicate functionality. I would suggest something like:
- If the configured header style for the rule is :setext_with_atx
  - call header_style to identify the current header style of the header you are considering, which will return one of atx or setext.
  - If it's atx, verify whether the level is greater than 2. This can be done by looking at the `:level` parameter of the headers options. MD001 and MD002 show examples of this.
  - If it's less than 2, or not setext/atx, then flag the line with an error.

**Comment by xi** [comment]
I tried to apply the requsted changes. I am not too happy about the formatting of the long boolean expression. But at least it should work.

**Comment by mivok** [comment]
Thanks for fixing that. I fixed it up a little, and changed the option to be a document header style rather than a separate parameter, and it's merged.

**Comment by xi** [comment]
Thanks!

**Pull request closed without merging**
