### PR TITLE
Add further documentation on custom rules

### PR DESCRIPTION
**Pull request by adamroyjones**
## Description
I struggled a little with getting custom rules to be loaded and used by
markdownlint. This merge request adds further documentation around this
process. This should hopefully ease this process for other developers.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (non-breaking change that does not add functionality but updates documentation)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/markdownlint/markdownlint/blob/master/CONTRIBUTING.md) document.
- [x] Wrote [good commit messages](https://chris.beams.io/posts/git-commit/)
- [x] Feature branch is up-to-date with `master`, if not - rebase it
- [x] Added tests for all new/changed functionality, including tests for positive and negative scenarios
- [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences

### CODE REVIEW

**Comment by adamroyjones** [comment]
I'm sorry that this came as something unsolicited—let me know if there are any issues or changes you'd like and I'll be happy to oblige.

**Review by jaymzh — APPROVED** [review]
awesome, thanks!

**Comment by jaymzh** [comment]
Looks like you need a signed-off-by line, the DCO check is failing.

**Comment by adamroyjones** [comment]
Thanks for the review!

> Looks like you need a signed-off-by line, the DCO check is failing.

Quite right—I've now updated my branch (in-place).

**Comment by jaymzh** [comment]
Your sign-off is by me. That's not right. Sign off your *own* work. It's stating you have permission to submit the changes, etc.

https://github.com/chef/chef/blob/main/CONTRIBUTING.md#developer-certification-of-origin-dco is a good explanation of it.

**Review by jaymzh — CHANGES_REQUESTED** [review]
Please add your DCO. Thanks.

**Comment by adamroyjones** [comment]
I've updated it again.

I'm sorry—when the CI pipeline prompted me to add a line about my work being "signed-off", I assumed it would mean by quite literally anyone _but_ me.

**Review by jaymzh — APPROVED** [review]

**Comment by jaymzh** [comment]
Thanks!

**Comment by adamroyjones** [comment]
Any time—and I'm sorry for my confusion around DCOs.

**Pull request merged**
